backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

locale: "sk"

collections:
  - label: "Stránky"
    name: "pages"
    files:
      - label: "Hlavná stránka"
        name: "home"
        file: "content/homepage.json"
        fields:
          - label: Kategória
            name: category
            widget: list
            fields:
              - { label: Názov, name: label, widget: string }
              - { label: Popis, name: description, widget: string }
              - label: Produkty
                name: products
                widget: list
                fields:
                  - { label: Názov, name: label, widget: string }
                  - { label: Popis, name: description, widget: string }
                  - { label: Gramáž, name: weight, widget: number }
                  - {
                      label: Cena,
                      name: price,
                      widget: number,
                      value_type: "float",
                    }
