backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: "images/uploads"

public_folder: "/images/uploads"

locale: "sk"

collections:
  - label: "Stránky"
    name: "pages"
    files:
      - label: "Typy pizze"
        name: "pizzaTypes"
        file: "content/pizza.json"
        fields:
          - label: "Pizze"
            name: "pizza"
            widget: "list"
            fields:
              - { label: "Názov", name: "label", widget: "string" }
              - { label: "Popis", name: "description", widget: "string" }
              - label: "Produkty"
                name: "products"
                widget: "list"
                fields:
                  - { label: "Názov", name: "label", widget: "string" }
                  - { label: "Číslo", name: "number", widget: "number" }
                  - { label: "Popis", name: "description", widget: "string" }
                  - {
                      label: "Gramáž",
                      name: "weight",
                      widget: "number",
                      required: false,
                    }
                  - {
                      label: "Cena",
                      name: "price",
                      widget: "number",
                      value_type: "float",
                    }
      - label: "Niečo iné z cesta"
        name: "posuchy"
        file: "content/posuchy.json"
        fields:
          - { label: "Názov", name: "label", widget: "string" }
          - {
              label: "Gramáž",
              name: "weight",
              widget: "number",
              required: false,
            }
          - label: "Produkty"
            name: "products"
            widget: "list"
            fields:
              - { label: "Názov", name: "label", widget: "string" }
              - {
                  label: "Cena",
                  name: "price",
                  widget: "number",
                  value_type: "float",
                }
      - label: "Panuozzo"
        name: "panuozzo"
        file: "content/panuozzo.json"
        fields:
          - label: "Panuozzo"
            name: "panuozzo"
            widget: "list"
            fields:
              - { label: "Názov", name: "label", widget: "string" }
              - { label: "Popis", name: "description", widget: "string" }
              - {
                  label: "Gramáž",
                  name: "weight",
                  widget: "number",
                  required: false,
                }
              - {
                  label: "Cena",
                  name: "price",
                  widget: "number",
                  value_type: "float",
                }
      - label: "Pizza tyčinky"
        name: "pizzaSticks"
        file: "content/sticks.json"
        fields:
          - { label: "Názov", name: "label", widget: "string" }
          - { label: "Kusy", name: "pieces", widget: "number", required: false }
          - label: "Produkty"
            name: "products"
            widget: "list"
            fields:
              - { label: "Názov", name: "label", widget: "string" }
              - {
                  label: "Cena",
                  name: "price",
                  widget: "number",
                  value_type: "float",
                }
      - label: "Prílohy"
        name: "additions"
        file: "content/additions.json"
        fields:
          - label: "Prílohy"
            name: "additions"
            widget: "list"
            fields:
              - { label: "Prílohy", name: "label", widget: "string" }
              - {
                  label: "Cena",
                  name: "price",
                  widget: "number",
                  value_type: "float",
                }
      - label: "Informácie"
        name: "informations"
        file: "content/informations.json"
        fields:
          - label: "Otváracie hodiny"
            name: "openingHours"
            widget: "list"
            fields:
              - {
                  label: "Otvorené",
                  name: "isOpen",
                  widget: "boolean",
                  required: false,
                  default: true,
                }
              - {
                  label: "Od",
                  name: "opens",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Do",
                  name: "closes",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Dni",
                  name: "dayOfWeek",
                  widget: "select",
                  multiple: true,
                  options:
                    [
                      "Monday",
                      "Tuesday",
                      "Wednesday",
                      "Thursday",
                      "Friday",
                      "Saturday",
                      "Sunday",
                    ],
                  default: ["Monday"],
                }
